name: Axelera Framework CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  ARCH: amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Folders
      working-directory: ${{github.workspace}}
      run: mkdir -p build_${{env.ARCH} && mkdir -p test_build_${{env.ARCH}}
    
    - name: Build
      working-directory: ${{github.workspace}}
      # Build the framwork
      run: ./docker.sh --verbose --github ./build.sh --build-dir build_${{env.ARCH}} --build-type ${{env.BUILD_TYPE}} --clean

    - name: C++ Unit Test & Python Test
      working-directory: ${{github.workspace}}
      # C++ Unit Test
      run: ./docker.sh --verbose --github ./test.sh --build-dir test_build_${{env.ARCH}} --build-type ${{env.BUILD_TYPE}} --clean
  
